Input:
    base_path: D:\DHIMC
    result_folders: [ExportResultsAshburton, ExportResultsAshley, ExportResultsOpihi, ExportResultsTemuka]
    file_index: file_index.json
    min_file_size: 30000
    scheduling:
      delay: 10
      frequency: 600
Output:
    server: SQL03prod
    database: Hydrotel
    sample_table: SampleBuf
    quality_code: 2
